name: generate pacman contribution graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ziqiwang20

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: output
