name: generate pacman contribution graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman contribution graph
        run: |
          mkdir -p dist
          npx pacman-contribution-graph --github-user-name ziqiwang20 --output dist/pacman-contribution-graph.svg --output-dark dist/pacman-contribution-graph-dark.svg

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
